name: movie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.3
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  gap: ^3.0.1
  http: ^1.1.2
  http_interceptor: ^2.0.0-beta.7
  provider: ^6.1.1
  responsive_sizer: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/


  fonts:
  - family: Rubik Medium
    fonts:
      - asset: assets/fonts/rubik_medium.ttf
      - asset: assets/fonts/rubik_regular.ttf